[package]
name = "ephemeris-app"
description = "Ephemeris application binary"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "ephemeris"
path = "src/main.rs"

[dev-dependencies]
tempfile = "3"

[dependencies]
ephemeris-core = { workspace = true, features = ["ics"] }
ephemeris-pal  = { workspace = true }
ephemeris-ui   = { workspace = true }
log = { workspace = true }
slint = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
winit = { workspace = true }
